# A name for this specific experiment run, used for creating output directories
task_name: "hde_imagenet_pretrain"

# 1. Model Architecture Configuration
model:
  img_size: 224
  patch_size: 16
  in_channels: 3

  # Encoder Configuration (from ViT model)
  encoder_embed_dim: 768
  encoder_depth: 12
  encoder_heads: 12
  
  # Decoder Configuration
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_heads: 16
  
  # HDE-specific Configuration
  visible_fraction: 0.25 # Corresponds to a 75% mask/noise ratio

# 2. Training Hyperparameters
training:
  optimizer: "AdamW"
  learning_rate: 0.0012 # A good starting point, may need tuning
  betas: [0.9, 0.95]
  weight_decay: 0.05
  
  warmup_epochs: 40
  eta_min: 0.000001 # Corresponds to lr_min in many schedulers
  
  num_epochs: 800
  batch_size: 512

  # Technical flags
  use_compile: false
  use_fused_optimizer: false
  gradient_accumulation_steps: 1
