# Configuration for SAM-B Variant on S8D Segmentation

task_name: "sam_b_s8d_run"

# 1. Model Configuration
model:
  # SAM variant 会根据 img_size 自动计算 patch_size 和 in_chans
  img_size: 8192 # 调整输入尺寸以适应显存
  target_patch_grid_size: 64 # 512 / 32 = patch_size 16
  pretrained: False # 加载 SAM 编码器权重
  num_classes: 5 # s8d 有 5 个类别
  # SAM 解码器通道配置 (可以调整)
  decoder_channels: [128, 64, 32, 16]

# 2. Training Hyperparameters
training:
  optimizer: "AdamW"
  learning_rate: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.05
  warmup_epochs: 5
  eta_min: 0.000001

  num_epochs: 100
  batch_size: 1 # SAM 可能也需要较小 batch size
  gradient_accumulation_steps: 8

  use_compile: False

# 3. Data Configuration
data:
  # !! 修改为您的 s8d 数据集切片目录 !!
  data_dir: '/work/c30636/dataset/s8d/finetune/Noise_1_Blur_2_sparsity_2_NumAng_3600/'
  num_workers: 8

# 4. Output Configuration
output:
  base_dir: './output'
  save_dir: 'sam_b_s8d_run'
