# Configuration for U-Net on S8D Segmentation (8k Resolution)

task_name: "unet_resnet34_s8d_8k_run" # 更新任务名称

# 1. Model Configuration
model:
  backbone_name: 'resnet34' # 使用 ResNet34，基于之前的 8k 测试
  pretrained: False
  in_chans: 1 # s8d 是单通道 (原始 8192x8192x1)
  num_classes: 5 # s8d 有 5 个类别 (包括背景, 目标掩码 8192x8192x5)
  img_size: 8192 # !! 修改: 使用原始 8k 分辨率 !!

# 2. Training Hyperparameters
training:
  optimizer: "AdamW"
  learning_rate: 0.0001 # 保持较低的学习率
  betas: [0.9, 0.999]
  weight_decay: 0.05
  warmup_epochs: 5
  eta_min: 0.00001

  num_epochs: 100
  batch_size: 1 # !! 修改: 由于使用 8k 分辨率，batch size 必须设为 1 !!
  gradient_accumulation_steps: 16 # !! 修改: 增加梯度累积步数以补偿小 batch size (1 * 16 = 16) !!

  use_compile: False

# 3. Data Configuration
data:
  # !! 修改为您的 s8d 数据集切片目录 (包含 slice_manifest.csv) !!
  data_dir: '/work/c30636/dataset/s8d/finetune/Noise_1_Blur_2_sparsity_2_NumAng_3600/'
  num_workers: 8 # 处理大图像时，可以适当减少 num_workers 以节省 CPU 内存

# 4. Output Configuration
output:
  base_dir: './output' # 保持输出根目录
  save_dir: 'unet_resnet34_s8d_8k_run' # 更新保存目录名称