# Configuration for the Baseline Vision Transformer (ViT) Model

# A name for this specific experiment run, used for creating output directories
task_name: "vit_imagenet_local_test"

# 1. Model Architecture Configuration
model:
  img_size: 256
  patch_size: 16
  in_channels: 3
  embed_dim: 768
  depth: 6
  num_heads: 12
  mlp_ratio: 4.0
  num_classes: 1000
  # layer_scale_init_value: 1e-6

# 2. Training Hyperparameters
training:
  optimizer: "AdamW"
  learning_rate: 0.0008
  weight_decay: 0.05
  warmup_epochs: 10 

  num_epochs: 300
  batch_size: 1280 # Adjust based on your DDP setup (e.g., 256 total / 8 nodes = 32 per node)

  use_compile: true                # 推荐：开启模型编译
  use_fused_optimizer: true        # 推荐：开启融合优化器
  gradient_accumulation_steps: 1
