# Configuration for the Baseline Vision Transformer (ViT) Model

# A name for this specific experiment run, used for creating output directories
task_name: "vit_imagenet_local_test"

# 1. Model Architecture Configuration
model:
  use_fp8: True
  img_size: 256
  patch_size: 16
  in_channels: 3
  embed_dim: 768
  depth: 6
  num_heads: 12
  mlp_ratio: 4.0
  num_classes: 1000

# 2. Training Hyperparameters
training:
  optimizer: "AdamW"
  learning_rate: 0.0001
  weight_decay: 0.05
  scheduler: "CosineAnnealingLR"
  min_lr: 1.0e-6
  num_epochs: 120
  batch_size: 1024 # Adjust based on your DDP setup (e.g., 256 total / 8 nodes = 32 per node)
